### ISSUE TITLE
In case of empty query results error with non-existing results file

### ISSUE THREAD

**Issue by smartfin** [yii2tech/csv-grid#1]
Steps to reproduce:

1) Use ActiveDataProvider + query, that return 0 results. 
2) Try to save results `$exporter->export()->saveAs('file.csv');`

Expecting to get empty file.

```
PHP Warning 'yii\base\ErrorException' with message 'rename(,file.csv): No such file or directory'

in /vagrant/vendor/yii2tech/csv-grid/ExportResult.php:173

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'rename(,file.cs...', '/vagrant/vendor...', 173, Array)
#1 /vagrant/vendor/yii2tech/csv-grid/ExportResult.php(173): rename('', 'file.csv')
#2 /vagrant/vendor/yii2tech/csv-grid/ExportResult.php(187): yii2tech\csvgrid\ExportResult->move('file.csv')
#3 /vagrant/console/controllers/InvoiceController.php(78): yii2tech\csvgrid\ExportResult->saveAs('file.csv')
#4 [internal function]: console\controllers\InvoiceController->actionDailyBackup()
#5 /vagrant/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#6 /vagrant/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#7 /vagrant/vendor/yiisoft/yii2/console/Controller.php(108): yii\base\Controller->runAction('daily-backup', Array)
#8 /vagrant/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('daily-backup', Array)
#9 /vagrant/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('invoice/daily-b...', Array)
#10 /vagrant/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('invoice/daily-b...', Array)
#11 /vagrant/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /vagrant/yii(27): yii\base\Application->run()
#13 {main}
```

**Comment by klimov-paul** [comment]
Resolved by commit ef9af796e1f4bc06272f0e87166825d176f93419
